function(ADD_TINYGLTF_PROJECT project_name)
	set(PROJECT_SOURCES ${ARGN})
	message(STATUS "Adding project ${project_name} with sources ${PROJECT_SOURCES}")
	add_executable(${project_name} ${PROJECT_SOURCES})
	target_link_libraries(${project_name} PRIVATE ${EXEC_LIBS})
	target_include_directories(${project_name} PRIVATE ${EXEC_INCLUDE_DIRS})
	add_dependencies(${project_name} CopyModels)
endfunction()